import { Realm } from "@realm/react";

export const TravelLocalSchema = {
  name: "TravelLocal",
  primaryKey: "id",
  properties: {
    id: "int",
    travel_id: "int",
    uuid: "string?",
    location_sequence: "int",
    location_description: "string?",
    location_type_id: "int",
    location_type_description: "string?",
    location_latitud: "string?",
    location_longitud: "string?",
    estimated_time: "string?",
    location_owner_id: "int",
    location_owner_name: "string?",
    location_arrive_schedule: "string?",
    location_depart_schedule: "string?",
    address: "string?",
    observation: "string?",
    status: "string?",
    start: "string?",
    end: "string?",
    date: "string?",
    merged: "string?",
    qty_delivery: "int",
    qty_collect: "int",
    not_confirmed: "int",
    total_missions: "int",
    confirmed_missions: "int",
    status_missions: "string?",
    wazer: "string?",
    google_maps: "string?",
    apple_maps: "string?",
    icon: "string?",
  },
};
